#!/bin/bash
# Manual Build and Start Guide for Redeemer Lab
# Use these commands if automated scripts don't work

echo "=========================================="
echo "  Redeemer Lab - Manual Setup Guide"
echo "=========================================="
echo ""
echo "Run these commands one by one:"
echo ""
echo "# Step 1: Navigate to project directory"
echo "cd /home/joyboy/THINGS/Internship/Redeemer"
echo ""
echo "# Step 2: Build the Redis image"
echo "docker compose build redis"
echo ""
echo "# Step 3: Build the OS instance image"
echo "docker compose build os-instance"
echo ""
echo "# Step 4: Start all services in background"
echo "docker compose up -d"
echo ""
echo "# Step 5: Wait for services to initialize (30-60 seconds)"
echo "sleep 30"
echo ""
echo "# Step 6: Check if services are running"
echo "docker compose ps"
echo ""
echo "# Step 7: Check Redis is responding"
echo "docker exec redeemer-redis redis-cli PING"
echo ""
echo "# Step 8: Check flag exists"
echo "docker exec redeemer-redis redis-cli GET flag"
echo ""
echo "# Step 9: Check health API"
echo "curl http://localhost:9001/api/status"
echo ""
echo "# Step 10: Access the lab"
echo "# Open browser: http://localhost:6080"
echo ""
echo "=========================================="
echo "  Stopping the Lab"
echo "=========================================="
echo ""
echo "# Stop services"
echo "docker compose down"
echo ""
echo "# Stop and remove all data"
echo "docker compose down -v"
echo ""
